### ISSUE TITLE
polyfill didn't work in worker thread

### ISSUE THREAD

**Issue by jimmywarting** [creatorrr/web-streams-polyfill#11]
Tried including the polyfill in web workers
But the stream api wasn't added to the global scope since it don't have window

```js
if ( typeof window !== "undefined" )
  Object.assign( window, interfaces );
```

**Comment by creatorrr** [comment]
Oh crap. This is my bad. Should be a simple fix, will push it soon.

**Comment by jimmywarting** [comment]
Thanks 

For now i just did this temporarily 

```js
var window = this
includeScript('polyfill.min.js')
```
