### ISSUE TITLE
using in npm

### ISSUE THREAD

**Issue by karissa** [creatorrr/web-streams-polyfill#2]
When one uses `require(web-streams-polyfill)` it isn't installing the `spec` directory and that content isn't included in the minified version, so you get errors like 

```
app.js:1 Error: Cannot find module './spec/reference-implementation/lib/writable-stream'
```

Could you fix the build process so the package is requirable on `npm`? thank you!

**Comment by derhuerst** [comment]
Adding `"spec"` to the `files` field in `package.json` would solve the issue?

**Comment by derhuerst** [comment]
I just noticed that the following works for me:

```
npm install web-streams-polyfill
node -e 'require("web-streams-polyfill")'
```

**Comment by jimmywarting** [comment]
Think #1 can solve this

**Comment by jimmywarting** [comment]
I'm. Just spekulating but maybe this will work in the meanwhile...?

require("web-stream-pollyfil/dist/polyfill.min.js")

**Comment by creatorrr** [comment]
Hmm, I don't understand why this is happening. The [package.json](https://github.com/creatorrr/web-streams-polyfill/blob/master/package.json) declares the `main` and `browser` scripts properly. Will investigate further.

**Comment by neovov** [comment]
I tried using this polyfill in a browserify workflow and stumble upon this issue.
It seems that browserify [cannot use an already browserified file](https://github.com/substack/node-browserify/pull/1151). I tried by changing the bundle task, adding a [`derequire`](https://github.com/calvinmetcalf/derequire) and it seems to work.

Sorry, I don't have time to send you a pull request right now, but you can change this, in the `package.json` file:
```json
"bundle": "browserify index.es6.js -s default -o dist/polyfill.js -t [ babelify ]",
```

With:
```json
"bundle": "browserify index.es6.js -s default -t [ babelify ] | derequire > dist/polyfill.js",
```
(and add the `derequire` as `devDependencies`)

**Comment by creatorrr** [comment]
Done @neovov

**Comment by karissa** [comment]
thank you!
