### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by TimothyGu** [creatorrr/web-streams-polyfill#4]
Hi, commit 68f93d7240d925d27b175ce39133f57993c3f109 bumped the version to 1.3.0, but unfortunately 1.3.0 is not yet published on npm. Could you please do so? Thanks!

**Comment by creatorrr** [comment]
@TimothyGu sorry about that, just bumbed the version to 1.3.1 and [published](https://www.npmjs.com/package/web-streams-polyfill).
