### ISSUE TITLE
Submodule definition conflicts with GitHub pages

### ISSUE THREAD

**Issue by DeadlySystem** [creatorrr/web-streams-polyfill#7]
I'd like to use your polyfill with GitHub pages by using it as a submodule, but that does not work because GitHub only supports HTTPS submodule dependencies ( https://help.github.com/articles/page-build-failed-invalid-submodule/ ). Could you update your WhatWG Spec dependency to use HTTPS instead of SSH?

**Comment by neovov** [comment]
This should do the trick : https://github.com/creatorrr/web-streams-polyfill/pull/8

**Comment by creatorrr** [comment]
Thanks for the fix, @neovov !
